network.host: 0.0.0.0
http.port: 9200
transport.tcp.port: 9300
node.name: "node-1"
discovery.seed_hosts: ["127.0.0.1","172.17.0.1"]
cluster.initial_master_nodes: ["node-0", "node-1"]

# # 启用密码
#xpack.security.enabled: true
#xpack.security.transport.ssl.enabled: true