network.host: 0.0.0.0
http.port: 9200
transport.tcp.port: 9300
node.name: "node-0"
discovery.seed_hosts: ["127.0.0.1:9300","82.156.80.115:9301"]
cluster.initial_master_nodes: ["127.0.0.1:9300", "82.156.80.115:9301"]

# 启用密码
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true