version: "3.3"

networks:
  es-net:
    driver: bridge

services:
  elasticsearch:
    image: registry.cn-hangzhou.aliyuncs.com/douyacun/elasticsearch:latest
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - es-net
    volumes:
      - ~/Documents/github.com/tools/docker/elasticsearch/data:/usr/share/elasticsearch/data
      - ~/Documents/github.com/tools/docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kibana:
    image: docker.io/kibana:7.5.0
    container_name: kibana
    networks:
      - es-net
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
