version: "3"

services:
  mysql:
    image: mysql:5.7.29
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ROOT_HOST: "0.0.0.0/0"
    ports:
      - 3308:3306
    volumes:
      - /Users/admin/Documents/tools/docker/db/mysql:/var/lib/mysql
